version: "3.9"
services:
  app.test:
    extends:
      file: docker-compose.base.yml
      service: app.test
    restart: unless-stopped
  node:
    extends:
      file: docker-compose.base.yml
      service: node
  mysql:
    extends:
      file: docker-compose.base.yml
      service: mysql
    restart: always
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis
    restart: unless-stopped
  mailhog:
    extends:
      file: docker-compose.base.yml
      service: mailhog
    restart: unless-stopped
networks:
  houstonnetwork:
    driver: "bridge"
volumes:
  mysqldata:
    driver: "local"
  redisdata:
    driver: "local"
