version: "3.9"
services:
  app:
    extends:
      file: docker-compose.base.yml
      service: app.test
  node:
    extends:
      file: docker-compose.base.yml
      service: node
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis
  mysql:
    extends:
      file: docker-compose.base.yml
      service: mysql
networks:
  houstonnetwork:
    driver: "bridge"
volumes:
  houstonmysql:
    driver: "local"
  houstonredis:
    driver: "local"
