version: "3.9"
services:
  app.test:
    build:
      context: ./vendor/withoutfanfare/houston/runtimes/7.4
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
    image: houston-7.4/php
    ports:
      - "${APP_PORT:-80}:80"
    environment:
      WWWUSER: "${WWWUSER}"
      HOUSTON_DOCKER: 1
    volumes:
      - .:/var/www/html
    networks:
      - houstonnetwork
    depends_on:
      - mysql
      - redis
      # - selenium
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
  node:
    build:
      context: ./vendor/withoutfanfare/houston/runtimes/node
      dockerfile: Dockerfile
    image: node
    volumes:
      - .:/var/www/html
    networks:
      - houstonnetwork

  mysql:
    image: "mysql:5.7"
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    expose:
      - 3306
    volumes:
      - mysqldata:/var/lib/mysql
      - ./vendor/withoutfanfare/houston/runtimes/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - houstonnetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]

  redis:
    image: "redis:alpine"
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - "houstonredis:/data"
    networks:
      - houstonnetwork
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "${FORWARD_MAILHOG_PORT:-1025}:1025"
      - "${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025"
    networks:
      - houstonnetwork
