version: "3.9"
services:
  app:
    extends:
      file: docker-compose.base.yml
      service: app.test
  node:
    extends:
      file: docker-compose.base.yml
      service: node
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis
  mysql:
    extends:
      file: docker-compose.base.yml
      service: mysql
networks:
  docker-network:
    driver: "bridge"
volumes:
  mysqldata:
    driver: "local"
  redisdata:
    driver: "local"
