# For more information: https://laravel.com/docs/houston
version: "3"
services:
  laravel.test:
    build:
      # context: ./docker/7.4
      context: ./vendor/withoutfanfare/houston/runtimes/7.4
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
    image: houston-7.4/app
    ports:
      - "${APP_PORT:-80}:80"
    environment:
      WWWUSER: "${WWWUSER}"
      HOUSTON_DOCKER: 1
    volumes:
      - ".:/var/www/html"
    networks:
      - houston
    depends_on:
      - mysql
      # - pgsql
      - redis
      # - selenium
  # selenium:
  #     image: 'selenium/standalone-chrome'
  #     volumes:
  #         - '/dev/shm:/dev/shm'
  #     networks:
  #         - houston
  mysql:
    # image: "mysql:8.0"
    image: "mysql:5.7"
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "houstonmysql:/var/lib/mysql"
    networks:
      - houston
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
  redis:
    image: "redis:alpine"
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - "houstonredis:/data"
    networks:
      - houston
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
  # memcached:
  #     image: 'memcached:alpine'
  #     ports:
  #         - '11211:11211'
  #     networks:
  #         - houston
  mailhog:
    image: "mailhog/mailhog:latest"
    ports:
      - "${FORWARD_MAILHOG_PORT:-1025}:1025"
      - "${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025"
    networks:
      - houston
networks:
  houston:
    driver: bridge
volumes:
  houstonmysql:
    driver: local
  houstonredis:
    driver: local
